command:
  scale:
    base: service
    parameters:
      agent_name:
        parser: variables
        type: str
        optional: true
        help: 'space separated agent name'
        value_label: NAME
        tags: [agent]
      agent_count:
        parser: variable
        type: str
        optional: '--count'
        help: 'integer count of agent services'
        value_label: COUNT
        tags: [agent]
    parse:
      agent_name:
      agent_count:

  service:
    priority: 35
    lock:
      set:
        base: state
        api_enabled: false
        require_db: false
        parameters:
          key:
            parser: variable
            type: str
            optional: False
            help: 'service key'
            value_label: KEY
            tags: [service_lock]
          expires:
            parser: variable
            type: int
            optional: True
            default: null
            help: 'key expiration in seconds'
            value_label: SEC
            tags: [service_lock]
        parse:
          key:
          expires:
      clear:
        base: state
        api_enabled: false
        require_db: false
        parameters:
          keys:
            parser: variables
            type: str
            optional: False
            help: 'one or more service keys'
            value_label: KEYS
            tags: [service_lock]
        parse:
          keys:
      wait:
        base: state
        api_enabled: false
        require_db: false
        parameters:
          keys:
            parser: variables
            type: str
            optional: False
            help: 'one or more service keys'
            value_label: KEYS
            tags: [service_lock]
          timeout:
            parser: variable
            type: int
            optional: '--timeout'
            default: 600
            help: 'wait timeout in seconds'
            value_label: SEC
            tags: [service_lock]
          interval:
            parser: variable
            type: int
            optional: '--interval'
            default: 1
            help: 'poll interval during wait period in seconds'
            value_label: SEC
            tags: [service_lock]
        parse:
          keys:
          timeout:
          interval:
    follow:
      base: service
      parameters:
        channel:
          parser: variable
          type: str
          optional: false
          help: 'communication channel'
          value_label: NAME
          tags: [messages]
        state_key:
          parser: variable
          type: str
          optional: '--state-key'
          help: 'state variable key'
          value_label: NAME
          tags: [messages]
        timeout:
          parser: variable
          type: int
          optional: '--timeout'
          default: 600
          help: 'wait timeout in seconds'
          value_label: SEC
          tags: [messages]
      parse:
        channel:
        state_key:
        timeout:
