# Generated by Django 5.2.1 on 2025-08-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0004_user_text_splitter_provider_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                ("label", models.CharField(max_length=256, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(data_name)s",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "memory",
                "verbose_name_plural": "memories",
                "db_table": "core_memory",
                "ordering": ["user", "name", "created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MemoryDialog",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs",
                        to="memory.memory",
                    ),
                ),
            ],
            options={
                "verbose_name": "memory dialog",
                "verbose_name_plural": "memory dialogs",
                "db_table": "core_memory_dialog",
                "ordering": ["memory_id", "created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MemoryMessage",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
                ),
                ("role", models.CharField(default="user", max_length=32)),
                ("sender", models.CharField(max_length=256, null=True)),
                ("content", models.TextField(default="")),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="memory.memorydialog",
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="memory.memory",
                    ),
                ),
            ],
            options={
                "verbose_name": "memory message",
                "verbose_name_plural": "memory messages",
                "db_table": "core_memory_message",
                "ordering": ["memory_id", "created"],
                "abstract": False,
            },
        ),
    ]
