name: ${ZIMAGI_APP_NAME}

include:
  - ./compose.network.yaml
  - ./compose.db.yaml

x-zimagi-build: &zimagi-build
  context: .
  dockerfile: ./docker/Dockerfile.server

x-zimagi-build-args: &zimagi-build-args
  ZIMAGI_ENVIRONMENT: ${ZIMAGI_ENVIRONMENT}
  ZIMAGI_USER_UID: ${ZIMAGI_USER_UID}

x-zimagi-env: &zimagi-env
  <<: *zimagi-build-args

  NVIDIA_VISIBLE_DEVICES: all
  NVIDIA_DRIVER_CAPABILITIES: compute,graphics,video,utility

  ZIMAGI_AUTO_UPDATE: false
  ZIMAGI_DISABLE_MODULE_INIT: false
  ZIMAGI_DISABLE_MODULE_SYNC: false
  ZIMAGI_RESTART_SERVICES: false

  ZIMAGI_RUNTIME_IMAGE: zimagi/server:nvidia-${ZIMAGI_ENVIRONMENT}
  ZIMAGI_DOCKER_RUNTIME: nvidia

  ZIMAGI_POSTGRES_HOST: postgresql-zimagi
  ZIMAGI_POSTGRES_PORT: 5432
  ZIMAGI_REDIS_HOST: redis-zimagi
  ZIMAGI_REDIS_PORT: 6379
  ZIMAGI_QDRANT_HOST: qdrant-zimagi
  ZIMAGI_QDRANT_PORT: 6333

x-zimagi-service-shared: &zimagi-service-shared
  env_file:
    - ./env/public.${ZIMAGI_PROFILE}
    - ./env/secret
    - ./.env
  networks:
    - zimagi-net
  group_add:
    - ${ZIMAGI_DOCKER_GID}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./lib:/usr/local/lib/zimagi
  depends_on:
    - postgresql-zimagi
    - redis-zimagi
    - qdrant-zimagi

x-zimagi-service: &zimagi-service
  <<: *zimagi-service-shared
  image: zimagi/server:${ZIMAGI_ENVIRONMENT}
  build:
    <<: *zimagi-build
    args:
      <<: *zimagi-build-args
      ZIMAGI_PARENT_IMAGE: ${ZIMAGI_STANDARD_BASE_IMAGE}
  environment:
    <<: *zimagi-env

x-zimagi-service-nvidia: &zimagi-service-nvidia
  <<: *zimagi-service-shared
  image: zimagi/server:nvidia-${ZIMAGI_ENVIRONMENT}
  build:
    <<: *zimagi-build
    args:
      <<: *zimagi-build-args
      ZIMAGI_PARENT_IMAGE: ${ZIMAGI_NVIDIA_BASE_IMAGE}
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  environment:
    <<: *zimagi-env

services:
  command-api:
    <<: *zimagi-service-nvidia
    entrypoint: zimagi-command
    ports:
      - '${ZIMAGI_COMMAND_PORT}:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/status']
      interval: 5s
      timeout: 5s
      retries: 60

  mcp-api:
    <<: *zimagi-service
    entrypoint: zimagi-mcp
    ports:
      - '${ZIMAGI_MCP_PORT}:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/status']
      interval: 5s
      timeout: 5s
      retries: 60

  data-api:
    <<: *zimagi-service
    entrypoint: zimagi-data
    ports:
      - '${ZIMAGI_DATA_PORT}:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/status']
      interval: 5s
      timeout: 5s
      retries: 60

  controller:
    <<: *zimagi-service
    entrypoint: zimagi-controller
    healthcheck:
      test: ['CMD-SHELL', 'test -f /var/local/zimagi/controller || exit 1']
      interval: 5s
      timeout: 5s
      retries: 60

  scheduler:
    <<: *zimagi-service
    entrypoint: zimagi-scheduler
    healthcheck:
      test: ['CMD-SHELL', 'test -f /var/local/zimagi/scheduler || exit 1']
      interval: 5s
      timeout: 5s
      retries: 60
