include:
  - ./compose.network.yaml

volumes:
  postgres_data: {}
  redis_data: {}
  qdrant_data: {}

services:
  postgresql:
    image: 'postgres:17.4'
    command: postgres -c 'max_connections=100'
    networks:
      - zimagi-net
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - ./env/public.${ZIMAGI_PROFILE}
      - ./env/secret
    ports:
      - '5432:5432'

  redis:
    image: 'redis:7.4.3'
    command: /bin/sh -c "redis-server --requirepass $$ZIMAGI_REDIS_PASSWORD"
    networks:
      - zimagi-net
    volumes:
      - 'redis_data:/data'
    env_file:
      - ./env/public.${ZIMAGI_PROFILE}
      - ./env/secret
    ports:
      - '6379:6379'
