include:
  - ./compose.network.yaml

volumes:
  postgres_zimagi_data: {}
  redis_zimagi_data: {}
  qdrant_zimagi_data: {}
  qdrant_zimagi_snapshots: {}

services:
  postgresql-zimagi:
    image: 'postgres:17.4'
    command: postgres -c 'max_connections=1000'
    networks:
      - zimagi-net
    volumes:
      - 'postgres_zimagi_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: zimagi
      POSTGRES_USER: zimagi
      POSTGRES_PASSWORD: ${ZIMAGI_POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d zimagi -U zimagi']
      interval: 1s
      timeout: 5s
      retries: 10

  redis-zimagi:
    image: 'redis:7.4.3'
    command: redis-server --requirepass ${ZIMAGI_REDIS_PASSWORD}
    networks:
      - zimagi-net
    volumes:
      - 'redis_zimagi_data:/data'
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'ping']
      interval: 1s
      timeout: 5s
      retries: 10

  qdrant-zimagi:
    image: 'qdrant/qdrant:v1.14.1'
    networks:
      - zimagi-net
    volumes:
      - 'qdrant_zimagi_data:/qdrant/storage'
      - 'qdrant_zimagi_snapshots:/qdrant/snapshots'
    environment:
      QDRANT__LOG_LEVEL: DEBUG
      QDRANT__STORAGE__SNAPSHOTS_PATH: /qdrant/snapshots
      QDRANT__STORAGE__TEMP_PATH: /qdrant/snapshots/tmp
      QDRANT__SERVICE__MAX_REQUEST_SIZE_MB: 1000
      QDRANT__SERVICE__API_KEY: ${ZIMAGI_QDRANT_ACCESS_KEY}
    ports:
      - '6333:6333'
      - '6334:6334'
    healthcheck:
      test: ['CMD-SHELL', 'bash -c ":> /dev/tcp/127.0.0.1/6333" || exit 1']
      interval: 5s
      timeout: 5s
      retries: 20
