name: zimagi-dev

include:
  - ./compose.db.yaml

x-zimagi-build: &zimagi-build
  context: .
  dockerfile: ./docker/Dockerfile.server

x-zimagi-build-args: &zimagi-build-args
  ZIMAGI_ENVIRONMENT: local

  ZIMAGI_USER_UID: ${ZIMAGI_USER_UID}
  ZIMAGI_USER_PASSWORD: ${ZIMAGI_USER_PASSWORD}
  ZIMAGI_DOCKER_GID: ${ZIMAGI_DOCKER_GID}

  ZIMAGI_DATA_KEY: ${ZIMAGI_DATA_KEY}

x-zimagi-env: &zimagi-env
  <<: *zimagi-build-args

  NVIDIA_VISIBLE_DEVICES: all
  NVIDIA_DRIVER_CAPABILITIES: compute,graphics,video,utility

  ZIMAGI_RUNTIME_IMAGE: zimagi/zimagi-gpu
  ZIMAGI_DOCKER_RUNTIME: nvidia

  ZIMAGI_POSTGRES_HOST: postgresql
  ZIMAGI_POSTGRES_PORT: 5432
  ZIMAGI_REDIS_HOST: redis
  ZIMAGI_REDIS_PORT: 6379

x-zimagi-service-shared: &zimagi-service-shared
  env_file:
    - ./env/public
    - ./env/secret
    - ./.env
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./app:/usr/local/share/zimagi
    - ./package:/usr/local/share/zimagi-client
    - ./lib:/usr/local/lib/zimagi
  depends_on:
    - postgresql
    - redis

x-zimagi-service: &zimagi-service
  <<: *zimagi-service-shared
  image: zimagi/zimagi
  build:
    <<: *zimagi-build
    args:
      <<: *zimagi-build-args
      ZIMAGI_PARENT_IMAGE: ubuntu:24.04
  environment:
    <<: *zimagi-env

x-zimagi-service-gpu: &zimagi-service-gpu
  <<: *zimagi-service-shared
  image: zimagi/zimagi-gpu
  build:
    <<: *zimagi-build
    args:
      <<: *zimagi-build-args
      ZIMAGI_PARENT_IMAGE: nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
  deploy:
    resources:
      reservations:
        devices:
          - capabilities:
              - gpu
  environment:
    <<: *zimagi-env

services:
  command-api:
    <<: *zimagi-service-gpu
    entrypoint: zimagi-command
    ports:
      - '5123:5000'

  data-api:
    <<: *zimagi-service
    entrypoint: zimagi-data
    ports:
      - '5323:5000'

  controller:
    <<: *zimagi-service
    entrypoint: zimagi-controller

  scheduler:
    <<: *zimagi-service
    entrypoint: zimagi-scheduler
    environment:
      <<: *zimagi-env
      ZIMAGI_DISABLE_MODULE_INIT: false

  tasks:
    <<: *zimagi-service
    entrypoint: celery-flower
    ports:
      - '5124:5000'
