name: ${ZIMAGI_APP_NAME}

include:
  - ./compose.network.yaml
  - ./compose.db.yaml

x-zimagi-build: &zimagi-build
  context: .
  dockerfile: ./docker/Dockerfile.server

x-zimagi-build-args: &zimagi-build-args
  ZIMAGI_ENVIRONMENT: ${ZIMAGI_ENVIRONMENT}
  ZIMAGI_USER_UID: ${ZIMAGI_USER_UID}

x-zimagi-env: &zimagi-env
  <<: *zimagi-build-args

  ZIMAGI_DISABLE_MODULE_INIT: true
  ZIMAGI_DISABLE_MODULE_SYNC: true
  ZIMAGI_RESTART_SERVICES: false

  ZIMAGI_RUNTIME_IMAGE: zimagi/server:${ZIMAGI_ENVIRONMENT}
  ZIMAGI_DOCKER_RUNTIME: standard

  ZIMAGI_POSTGRES_HOST: postgresql
  ZIMAGI_POSTGRES_PORT: 5432
  ZIMAGI_REDIS_HOST: redis
  ZIMAGI_REDIS_PORT: 6379

x-zimagi-service-shared: &zimagi-service-shared
  env_file:
    - ./env/public.${ZIMAGI_PROFILE}
    - ./env/secret
    - ./.env
  networks:
    - zimagi-net
  group_add:
    - ${ZIMAGI_DOCKER_GID}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./app:/usr/local/share/zimagi
    - ./package:/usr/local/share/zimagi-client
    - ./lib:/usr/local/lib/zimagi
  depends_on:
    - postgresql
    - redis

x-zimagi-service: &zimagi-service
  <<: *zimagi-service-shared
  image: zimagi/server:${ZIMAGI_ENVIRONMENT}
  build:
    <<: *zimagi-build
    args:
      <<: *zimagi-build-args
      ZIMAGI_PARENT_IMAGE: ${ZIMAGI_STANDARD_BASE_IMAGE}
  environment:
    <<: *zimagi-env

services:
  command-api:
    <<: *zimagi-service
    entrypoint: zimagi-command
    ports:
      - '5123:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/status']
      interval: 5s
      timeout: 5s
      retries: 20

  data-api:
    <<: *zimagi-service
    entrypoint: zimagi-data
    ports:
      - '5323:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/status']
      interval: 5s
      timeout: 5s
      retries: 20

  controller:
    <<: *zimagi-service
    entrypoint: zimagi-controller
    healthcheck:
      test: ['CMD-SHELL', 'test -f /var/local/zimagi/controller || exit 1']
      interval: 5s
      timeout: 5s
      retries: 20

  scheduler:
    <<: *zimagi-service
    entrypoint: zimagi-scheduler
    environment:
      <<: *zimagi-env
      ZIMAGI_AUTO_UPDATE: false
      ZIMAGI_DISABLE_MODULE_INIT: false
    healthcheck:
      test: ['CMD-SHELL', 'test -f /var/local/zimagi/scheduler || exit 1']
      interval: 5s
      timeout: 5s
      retries: 20

  tasks:
    <<: *zimagi-service
    entrypoint: celery-flower
    ports:
      - '5124:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000']
      interval: 5s
      timeout: 5s
      retries: 20
