#!/usr/bin/env bash
#
# Usage:
#
#  $> js-sdk <npm command> [args] [flags/options]
#
#=========================================================================================
# Environment
#
set -e

export __script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${__script_dir}/reactor/initialize.sh" zimagi "${__script_dir}"
#
#=========================================================================================
# Execution
#
export ZIMAGI_VERSION=$(cat "${__zimagi_app_dir}/VERSION")
export ZIMAGI_ENVIRONMENT="${COMPOSE_ENVIRONMENT:-local}"
export ZIMAGI_ENV_PROFILE="${COMPOSE_PROFILE:-default}"

ZIMAGI_COMMON_ARGS=(
  "--rm"
  "--interactive"
  "--tty"
  "--user" "$(id -u):zimagi"
  "--entrypoint" "npm"
  "--network" "host"
  "--volume" "${__zimagi_js_sdk_dir}:/usr/local/share/zimagi"
  "--volume" "${__zimagi_data_dir}:/var/local/zimagi"
  "--env-file" "${__zimagi_env_dir}/public.${ZIMAGI_ENV_PROFILE}"
  "--env-file" "${__zimagi_env_dir}/secret"
  "--env-file" "${__script_dir}/.env"
)
while IFS= read -r variable; do
  ZIMAGI_COMMON_ARGS=("${ZIMAGI_COMMON_ARGS[@]}" "--env" "$variable")
done <<< "$(env | grep -o "ZIMAGI_[_A-Z0-9]*")"

ZIMAGI_CLIENT_IMAGE="zimagi/cli:${ZIMAGI_VERSION}"
ZIMAGI_ARGS=("${ZIMAGI_COMMON_ARGS[@]}" "$ZIMAGI_CLIENT_IMAGE" "${@}")

if ! docker inspect "$ZIMAGI_CLIENT_IMAGE" >/dev/null 2>&1; then
  "${__zimagi_docker_dir}/build_client_image.sh" "${ZIMAGI_ENVIRONMENT}"
fi

docker run "${ZIMAGI_ARGS[@]}"
