#!/usr/bin/env bash
#
# Usage:
#
#  $> zimagi <command> [args] [flags/options]
#
#=========================================================================================
# Environment
#
set -e

export __script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${__script_dir}/reactor/initialize.sh" zimagi "${__script_dir}"
#
#=========================================================================================
# Execution
#
export ZIMAGI_VERSION=$(cat "${__zimagi_app_dir}/VERSION")
export ZIMAGI_ENVIRONMENT="${COMPOSE_ENVIRONMENT:-local}"
export ZIMAGI_ENV_PROFILE="${COMPOSE_PROFILE:-default}"

ZIMAGI_COMMON_ARGS=(
  "--rm"
  "--interactive"
  "--tty"
  "--user" "$(id -u):zimagi"
  "--volume" "${__zimagi_app_dir}:/usr/local/share/zimagi"
  "--volume" "${__zimagi_python_sdk_dir}:/usr/local/share/zimagi-client"
  "--volume" "${__zimagi_data_dir}:/var/local/zimagi"
  "--volume" "${__zimagi_lib_dir}:/usr/local/lib/zimagi"
  "--env-file" "${__zimagi_env_dir}/public.${ZIMAGI_ENV_PROFILE}"
  "--env-file" "${__zimagi_env_dir}/secret"
  "--env-file" "${__script_dir}/.env"
)
while IFS= read -r variable; do
  ZIMAGI_COMMON_ARGS=("${ZIMAGI_COMMON_ARGS[@]}" "--env" "$variable")
done <<< "$(env | grep -o "ZIMAGI_[_A-Z0-9]*")"

if [[ "${ZIMAGI_LOCAL_MODE:-}" ]] || [[ "${*}" == "build" ]] || [[ "${*}" == "build "* ]] || [[ "${*}" == "agent "* ]]; then
  ZIMAGI_SERVER_IMAGE="zimagi/server:${ZIMAGI_ENVIRONMENT}"
  ZIMAGI_ARGS=(
    "${ZIMAGI_COMMON_ARGS[@]}"
    "--network" "zimagi-net"
    "--env" "ZIMAGI_CLI_EXEC=True"
    "$ZIMAGI_SERVER_IMAGE" "${@}"
  )
else
  ZIMAGI_CLIENT_IMAGE="zimagi/cli:${ZIMAGI_VERSION}"
  ZIMAGI_ARGS=(
    "${ZIMAGI_COMMON_ARGS[@]}"
    "--network" "host"
    "$ZIMAGI_CLIENT_IMAGE" "${@}"
  )

  if ! docker inspect "$ZIMAGI_CLIENT_IMAGE" >/dev/null 2>&1; then
    "${__zimagi_docker_dir}/build_client_image.sh" "${ZIMAGI_ENVIRONMENT}"
  fi
fi
docker run "${ZIMAGI_ARGS[@]}"
