test_migrations:
  provider: command
  command: zimagi makemigrations --dry-run

build_migrations:
  provider: command
  command: zimagi makemigrations

migrate:
  provider: command
  command: zimagi migrate
