# Generated by Django 5.2.1 on 2025-07-18 03:48

import systems.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_temp_token_user_temp_token_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="encoder_provider",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="encoder_provider_options",
            field=systems.models.fields.DictionaryField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="language_provider",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="language_provider_options",
            field=systems.models.fields.DictionaryField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="search_limit",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="user",
            name="search_min_score",
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name="user",
            name="text_splitter_provider",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
