# Generated by Django 5.2.1 on 2025-07-19 17:04

import systems.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_encoder_provider_user_encoder_provider_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="text_splitter_provider_options",
            field=systems.models.fields.DictionaryField(default=dict),
        ),
    ]
