# Generated by Django 5.2.1 on 2025-07-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
