# Generated by Django 5.2.1 on 2025-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="label",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
