# Generated by Django 5.2.1 on 2025-07-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chat_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatDialog",
            fields=[
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs",
                        to="chat.chat",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chat.chatdialog",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat dialog",
                "verbose_name_plural": "chat dialogs",
                "db_table": "core_chat_dialog",
                "ordering": ["chat_id", "-created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="dialog",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatdialog",
            ),
            preserve_default=False,
        ),
    ]
