# Generated by Django 5.2.1 on 2025-07-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatdialog_chatmessage_dialog"),
        ("user", "0002_user_temp_token_user_temp_token_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(data_name)s",
                to="user.user",
            ),
            preserve_default=False,
        ),
    ]
