# Generated by Django 5.2.1 on 2025-07-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_chat_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={
                "ordering": ["user", "name", "created"],
                "verbose_name": "chat",
                "verbose_name_plural": "chats",
            },
        ),
        migrations.AlterModelOptions(
            name="chatdialog",
            options={
                "ordering": ["chat_id", "created"],
                "verbose_name": "chat dialog",
                "verbose_name_plural": "chat dialogs",
            },
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["chat_id", "created"],
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
            },
        ),
    ]
