# Generated by Django 5.2.1 on 2025-07-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chat_options_alter_chatdialog_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatdialog",
            name="previous",
        ),
    ]
