info:
  overview: |
    (local) Get existing environment

  description: |
    Gets the currently active environment, returning details about the environment such as the environment’s status, base image, runtime image, attached hosts, and included modules.

version:
  overview: |
    (local) Get client and environment versions

  description: |
    Returns the versions of both client and environment

host:
  overview: |
    (local) Manage environment hosts

  description: |
    Host commands let you interact with hosts tied to the current environment. Find active hosts, modify hosts, and remove hosts.

  list:
    overview: |
      (local) List environment hosts

    description: |
      Returns a list of all hosts mapped to the current local environment.

  get:
    overview: |
      (local) Get existing environment host

    description: |
      Get information about a specific host in the current environment. Takes ``host_name`` - The
      name of a host in the environment. If none is provided, defaults to ``@host_name|default.``

  save:
    overview: |
      (local) Save environment host

    description: |
      Add and save a new environment host. Takes ``field=Value`` - Key-value pairs specifying host configurations. Requires Key-value pair for ``host=URL``. Optional Key-value pairs - ``port``, ``user``,``token``.

  remove:
    overview: |
      (local) Remove an existing environment host

    description: |
      TODO

  clear:
    overview: |
      (local) Clear all environment hosts

    description: |
      Remove all hosts from the current environment. Takes one or more search queries.
