_volumes: &volumes
  /var/run/docker.sock:
    bind: /var/run/docker.sock
    mode: rw
  '@ZIMAGI_HOST_APP_DIR':
    bind: /usr/local/share/zimagi
    mode: ro
  '@ZIMAGI_HOST_PACKAGE_DIR':
    bind: /usr/local/share/zimagi-client
    mode: ro
  '@ZIMAGI_HOST_LIB_DIR':
    bind: /usr/local/lib/zimagi
    mode: rw

_zimagi: &zimagi
  image: '@ZIMAGI_RUNTIME_IMAGE'
  runtime: '@ZIMAGI_DOCKER_RUNTIME'
  inherit_environment: true
  wait: 5
  environment:
    ZIMAGI_POSTGRES_HOST: postgresql
    ZIMAGI_POSTGRES_PORT: 5432
    ZIMAGI_REDIS_HOST: redis
    ZIMAGI_REDIS_PORT: 6379
  volumes:
    <<: *volumes

services:
  postgresql:
    image: bitnami/postgresql:14.12.0
    wait: 1
    restart_policy:
      Name: always
    environment:
      POSTGRESQL_EXTRA_FLAGS: '-c max_connections=@ZIMAGI_POSTGRES_SERVICE_CONNECTIONS<< 1000 >>'
      POSTGRESQL_PASSWORD: '@ZIMAGI_POSTGRES_PASSWORD'
      POSTGRESQL_DATABASE: '@ZIMAGI_POSTGRES_DB'
    volumes:
      postgresql:
        bind: /bitnami/postgresql
        mode: rw
    ports: 5432/tcp

  redis:
    image: redis:7-bullseye
    wait: 1
    command: "redis-server --requirepass @ZIMAGI_REDIS_PASSWORD --client-output-buffer-limit 'pubsub 0 0 0'"
    restart_policy:
      Name: always
    ports: 6379/tcp
    volumes:
      redis:
        bind: /data
        mode: rw

  worker:
    <<: *zimagi
    template: true
    entrypoint: zimagi-worker

  agent:
    <<: *zimagi
    template: true
